import "../styles/global.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Discogs",
    template: "Discogs | %s",
  },
  description: "Generated by Next.js and CSS Module",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
